### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by radiatoryang** [jasonrsadler/FaceShapeDrivers#2]
I mostly want to use your hard-coded blendshape presets on Fuse characters' visemes for a lip sync project I'm working on over here: https://github.com/radiatoryang/lipstick

It'd help me out a lot if you added a license please, preferably MIT or something fairly permissive... thanks, hope you're well / thanks for your time

**Comment by UXVirtual** [comment]
@jasonrsadler I'd also be interested in knowing if you could add a licence for this too. Looking at an approach for re-targetting the facial expression blendshapes on Reallusion Character Creator 3 characters and also combining it with the viseme tagging from Oculus' Lip Sync implementation.
