### ISSUE TITLE
fuse cc + mixamo discontinued

### ISSUE THREAD

**Issue by icuruok** [jasonrsadler/FaceShapeDrivers#4]
blendshapes are not possible to do from fuse cc and mixamo anymore

As of September 28th, 2020 adobe fuse cc is no longer supporting uploads to mixamo directly thus facial blendshapes are no longer possible.

**Comment by jasonrsadler** [comment]
Indeed. That is unfortunate. Thank you for letting me know.

**Comment by jasonrsadler** [comment]
Updated readme with deprecation
